name: Generate Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Platane/snk@v2
      with:
        github_user_name: <your-username> # Replace with your GitHub username
        outputs: dist/snake.svg
    - uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: output
        build_dir: dist

